# Default values for datascientest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replica count configuration
replicaCount: 4

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
service:
  type: NodePort
  port: 80  # Uncomment and adjust the following line if you need a specific node port
  # nodePort: 30001  # Choose a port between 30000 and 32767 for NodePort

# Image pull secrets
imagePullSecrets: []

# Name overrides
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Pod security context
podSecurityContext: {}
  # fsGroup: 2000

# Security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Service configuration
service:
  type: NodePort
  port: 80
  # Uncomment and adjust the following line if you need a specific node port
  # nodePort: 30001  # Choose a port between 30000 and 32767 for NodePort

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  # Uncomment and adjust the following section if using TLS
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

# Resource limits and requests
resources: {}
  # Uncomment and modify the following lines to set resource limits and requests
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # Uncomment and adjust the following line if you want to use memory utilization for autoscaling
  # targetMemoryUtilizationPercentage: 80

# Additional volumes and volume mounts
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
